### ISSUE TITLE
Persistence not working in macOS

### ISSUE THREAD

**Issue by hammi1** [neoneggplant/EggShell#103]
After running persistence install or persistence uninstall (for macOS victim connected to eggshell running on Linux Mint 19) the persistence does not work. There is no reconnection occurring back to my host.

In the python code for persistence_macos.py, the commands show to only display the text "Installing" or "Uninstalling" but no code to actually run persistence, as is the case in the teensy payload py. I may be wrong as I am very limited in python knowledge but I think the code for macOS persistence (over bash) may be missing, or does not work for me.

Mac OS version is 10.10.5 (Yosemite) and my host is Linux Mint 19.

EDIT: Persistence seems to be working, I may have made an error initially. After exiting a session, it re-opens fairly quickly now (after closing and restarting eggshell). I will test if it sticks after rebooting. Is it perhaps necessary to run `persistence install` as root?

**Comment by lucasjacks0n** [comment]
it should work on root and non root, even after reboot
