### ISSUE TITLE
/del

### ISSUE THREAD

**Issue by ghost** [neoneggplant/EggShell#105]
**Hardware**: ipad mini 1
**Jailbreak Tool**: Phoenix
**Terminal**: WhiteTerminal

**Attacker Device**: Xiaomi Mi A1
**Attacker Device Terminal**: Termux

When I trying connect to my ipad , it stucked on this step:
Establishing secure connection.

**Comment by thehappydinoa** [comment]
Do you have root on the android device? You have to be root to open a port on the device. If it is not rooted I would suggest Magisk.
