### ISSUE TITLE
user error

### ISSUE THREAD

**Issue by iraizo** [neoneggplant/EggShell#108]
I want a mac to connect from a other network, im on osx i got my ip from the settings then just port scanned it and got an open tcp port if they tried to connect it says "operation timed out"

**Comment by thehappydinoa** [comment]
This will not work unless you set up [port-forwarding](https://www.noip.com/support/knowledgebase/general-port-forwarding-guide/) or [ngrok](https://ngrok.com/docs).

**Comment by iraizo** [comment]
Alright im gonna try ngrok out, thank you!

**Comment by thehappydinoa** [comment]
Also make sure to change the title of the issue as it is user error

**Comment by iraizo** [comment]
Im probaly too dumb to do it i should do ngrok tcp 1024 or something, right?

**Comment by thehappydinoa** [comment]
Try port 4444

**Comment by vivianfrench2** [comment]
I have a question. I am trying to use ngrok in EggShell. I type ngrok tcp 8080. Then, in Eggshell, I type the option of payload I want. After that, I type the LHOST=0.tcp.ngrok.io and the LPORT as 19335. Maybe I am typing the LHOST wrong or something, I don't know. I am using the info ngrok provides for me as a tunnel. The payload doesn't work as a result. What should I do?

**Comment by iraizo** [comment]
oh yeah am i still using my ip ?

**Comment by thehappydinoa** [comment]
No it's the hostname or ip ngork gives you

**Comment by vivianfrench2** [comment]
How do you find the IP ngrok gives you? I only see the hostname
0.tcp.ngrok.io!!!

**Comment by vivianfrench2** [comment]
How do you find the IP Ngrok gives you? I used the hostname 0.tcp.ngrok.io and it didn't work at all!!!!

**Comment by thehappydinoa** [comment]
It should be returned after setting up [TCP](https://ngrok.com/docs#tcp)

**Comment by vivianfrench2** [comment]
How do you set up TCP? Where do you see it returned?

**Comment by iraizo** [comment]
if i would use tcp://0.tcp.ngrok.io:18531 it would just not work "[Errno 8] nodename nor servname provided, or not known"

**Comment by vivianfrench2** [comment]
It would give me a different IP but it would not work.

**Comment by iraizo** [comment]
ok i got the ip etc but the ttl would go up but eggshell wont recognize

**Comment by iraizo** [comment]
> How do you find the IP Ngrok gives you? I used the hostname 0.tcp.ngrok.io and it didn't work at all!!!!

ping 0.tcp.ngrok.io

**Comment by vivianfrench2** [comment]
I tried that but it didn't work. Eggshell doesn't recognize the ip address.
😰😰😰
