### ISSUE TITLE
I rewrite for python3

### ISSUE THREAD

**Issue by enty8080** [neoneggplant/EggShell#129]
I rewrite EggShell for python3, but when I try to connect to my iphone I got the stuck on establishing secure connection.

Maybe problem in python3 socket.

**Comment by enty8080** [comment]
@neoneggplant are you interesting in your project?

**Comment by enty8080** [comment]
I rewrite for python3, add .encode() and .decode() and it really works!!!!!!!!!!! But download cannot download binary and upload cannot upload binary.

**Comment by vintendpower** [comment]
> I rewrite for python3, add .encode() and .decode() and it really works!!!!!!!!!!! But download cannot download binary and upload cannot upload binary.

Are you still working on this ? Any luck getting this to work with iOS 13

**Comment by 0xfffffff0075e2040** [comment]
[Community fork](https://github.com/rpwnage/EggShell-Community-Fork)
