### ISSUE TITLE
Error while build for armv7, arm64.

### ISSUE THREAD

**Issue by enty8080** [neoneggplant/EggShell#130]
```
> Making all for tool esplios…
==> Linking tool esplios (armv7)…
ld: in '/usr/lib/system/liblaunch.dylib', missing required architecture armv7 in file /usr/lib/system/liblaunch.dylib (2 slices) for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/enty8080/eggshell/src/esplios/.theos/obj/debug/armv7/esplios] Error 1
make[2]: *** [/Users/enty8080/eggshell/src/esplios/.theos/obj/debug/armv7/esplios] Error 2
make[1]: *** [internal-tool-all_] Error 2
make: *** [ios.all.tool.variables] Error 2
```

Please @neoneggplant or @nerdtron123 **HELP ME**, I am porting esplios for iOS13.

Also there is an error with libcrypto.a:

```
> Making all for tool esplios…
make[3]: *** No rule to make target `libcrypto.a', needed by `/Users/enty8080/eggshell/src/esplios/.theos/obj/debug/armv7/esplios'.  Stop.
make[2]: *** [/Users/enty8080/eggshell/src/esplios/.theos/obj/debug/armv7/esplios] Error 2
make[1]: *** [internal-tool-all_] Error 2
make: *** [ios.all.tool.variables] Error 2
```

**System:**

* `MacOS High Sierra 10.13.6`
* `Xcode 7.2.1`
* `SDK iPhoneOS9.3`
* `Theos latest version`

Waiting for @neoneggplant and @nerdtron123 help...

**Comment by enty8080** [comment]
**HEY**

**Comment by enty8080** [comment]
@neoneggplant

**Comment by enty8080** [comment]
@neoneggplant

**Comment by Spl01ter** [comment]
Same problem here

**Comment by Spl01ter** [comment]
[  8:19PM ]  [ ac@Macintosh:~/EggShell/src/esplios(master✗)(ruby-2.7.0) ]
 $ make
Makefile:1: /makefiles/common.mk: No such file or directory
Makefile:11: /tool.mk: No such file or directory
make: *** No rule to make target `/tool.mk'.  Stop.

**Comment by Spl01ter** [comment]
[  8:23PM ]  [ ac@Macintosh:~/EggShell/src/esplios(master✗)(ruby-2.7.0) ]
 $ gcc main.mm
In file included from main.mm:10:
./espl.h:10:9: fatal error: 'AppSupport/CPDistributedMessagingCenter.h' file not found
#import <AppSupport/CPDistributedMessagingCenter.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by enty8080** [comment]
@Spl01ter It's broken. @neoneggplant should update it.

And next time use `make` or `gcc -x objective-c -framework Foundation`
