### ISSUE TITLE
make it that we can drop binaries

### ISSUE THREAD

**Issue by nerdtron123** [neoneggplant/EggShell#16]
we could probably make a little database that has a bunch of tools allowing us to do a command 'root' and it'd automatically determine iOS version + device to find a proper jailbreak tool, so in turn we could get root if not running as root. I understand this is a payload application 🤷‍♂️ but we could expand it

**Comment by neoneggplant** [comment]
yeah, having privilege escalation is something I want to implement, there are so many we can use

**Comment by nerdtron123** [comment]
upload command
