### ISSUE TITLE
Running from ios

### ISSUE THREAD

**Issue by nerdtron123** [neoneggplant/EggShell#17]
http://python.mila432.com Python for iOS 10 :)

**Comment by neoneggplant** [comment]
does that work with pycrypto on 64 bit devices?

**Comment by nerdtron123** [comment]
I installed pycrypto but I'm still getting the you need to install pycrypto
error. You have to manually sign the binaries with ldid as shown on site.
If u want me to host eggshell on my repo at
https://apt.enduniverse.com/cydia then hmu

**Comment by neoneggplant** [comment]
awesome, let me know if you get it running on 64 bit devices, it is in high demand
