### ISSUE TITLE
More commands for MacOS?

### ISSUE THREAD

**Issue by mineo210** [neoneggplant/EggShell#28]
hey, I've been getting a lot of root shells with the rubberducky from my school since they use macbook air. but almost half of the commands I make is "exec" since there is not so "many" ones included. Will there be more commands for macOS in the future? and the "screenshot" command doesn't work even if I have root access, I need to type "exec screencapture -x 1.png"

**Comment by nerdtron123** [comment]
If you need more commands, request them.

**Comment by mineo210** [comment]
@nerdtron123 how ??

**Comment by neoneggplant** [comment]
I plan to add a lot more + system shell command support

**Comment by nerdtron123** [comment]
Close this issue and instead make other issues
