### ISSUE TITLE
Multiserver issue!?

### ISSUE THREAD

**Issue by mineo210** [neoneggplant/EggShell#29]
When I'm in a session and there's a new session getting connected I get kicked back to the "Multiserver menu" so I need to connect back to the session I was in.. this is pretty annoying if you are downloading something and you get kicked out of it just because there's a new session. Is this an issue or is this made on purpose?!

**Comment by nerdtron123** [comment]
you don't get kicked back, it's just bad shell handling, if you click enter you'll be right back in your session shell.

**Comment by mineo210** [comment]
@nerdtron123 do you know any more "tips" I would like to know more about eggshell. And is there anything else than trolling taking screenshots and taking isight pictures ??.. i dont really know what to do now with all of my sessions lmao..

**Comment by neoneggplant** [comment]
fixed this in the latest commit

**Comment by nerdtron123** [comment]
@mineo210 you have a bunch of sessions, you can sell those for money, you can make them be bitcoin mining slaves, etc
