### ISSUE TITLE
Issue when using option 1 (Start Server)

### ISSUE THREAD

**Issue by AppleManPS3** [neoneggplant/EggShell#3]
- Using iPad 2 (64GB) with iOS 9.3.3

- I press option one and the program will crash after going though setting up the LPORT

- If the program does not crash, it will freeze and not do anything and has to be closed via Task Manager.

I don't know what this error is but it should be fixed.

**Comment by hmksq** [comment]
Duplicate of #2

**Comment by neoneggplant** [comment]
when if freezes, does it say "listening on port xxxx"? And can you elaborate on what happens when it crashes, error messages would be helpful

**Comment by AppleManPS3** [comment]
It crashes/freezes when "Listening on port xxxx". When it crashes; it crashes. No errors, no message, nothing, the program just disappears.

**Comment by neoneggplant** [comment]
if you think its freezing, it's not, its listening for the connect back on your iOS device

**Comment by AppleManPS3** [comment]
What does that mean?

**Comment by Shugabuga** [comment]
@AppleManPS3 It's waiting for your iPhone to connect to EggShell. Did you install it to your device?

**Comment by neoneggplant** [comment]
@AppleManPS3 @Shugabuga read the documentation on http://lucasjackson.me/index.php/EggShell/
