### ISSUE TITLE
Session doesn't work!

### ISSUE THREAD

**Issue by mineo210** [neoneggplant/EggShell#36]
***this is what I get !***

[*]  Session 1 opened | root@USER MacBook Air 00.00.00.00
MultiSession> interact 1
[*]  type "help" for commands
root@USER MacBook Air> ls  
something went wrong
MultiSession> sessions
[*]  Total Sessions: 1
[Errno 22] Invalid argument

MultiSession>

What is happening ?? it worked before perfect, but now it doesn't for some reason :(

**Comment by neoneggplant** [comment]
made some bug fixes, let me know if it works now. If the bug fixes aren't related I will fix this asap <img width="346" alt="screen shot 2017-03-06 at 10 53 13 am" src="https://cloud.githubusercontent.com/assets/12518571/23617439/23da5a84-025b-11e7-9b90-24bf06df87bf.png">

**Comment by mineo210** [comment]
happens again :(
tho some of the sessions work perfect..

**Comment by mineo210** [comment]
I found this today a bit similar what I was thinking but is hard as fuck to get someone to run a python script with root :( https://github.com/manwhoami/Bella
would be cool if you guys could maybe work together or something. :))

**Comment by neoneggplant** [comment]
heard of bella, havent tried it yet. And is this only showing when you try "sessions"?

**Comment by mineo210** [comment]
yeah and  I got Bella working thanks to EggShell, Netcat and transfer.sh I just uploaded the payload to transfer.sh and then later download it via netcat with curl on a random shell and then later chmod it so i can run it with "./"  Bella is a python backdoor so i had to upload the code somehow.. lol bella isnt that good tho.

**Comment by neoneggplant** [comment]
with eggshell, you can now perform system commands, and do chmod/python somefile.py
