### ISSUE TITLE
Android soupport

### ISSUE THREAD

**Issue by cezarlacatus** [neoneggplant/EggShell#43]
As long as this shell works only on a jailbroaken ios you can make a same shell for android??There's no shell for android so cool like this...

Yhx and sorry for my englesh

**Comment by mineo210** [comment]
does android have bash?? There's a lot of rats for android try that.

**Comment by neoneggplant** [comment]
currently there is no binary payload for android, however, this could be done, I plan to do linux first before androidd

**Comment by cezarlacatus** [comment]
Cool please do it.You have nice features on iphones.I am so sad because this only works on a jailbroaken device _-_ apple sucks
