### ISSUE TITLE
There's a password recovery tool called LaZagne

### ISSUE THREAD

**Issue by mineo210** [neoneggplant/EggShell#45]
If you feel like adding this do you think it's possible to make a module out of this?

https://github.com/AlessandroZ/LaZagne

**Comment by neoneggplant** [comment]
hmm very interesting, definitely going to look into it!

**Comment by neoneggplant** [comment]
@mineo210 I created a lazagne command module, it seems firefox is the only thing it supports

**Comment by mineo210** [comment]
Wow awesome, no problem tho!

**Comment by mineo210** [comment]
Sadly tho it supports a lot more on Windows.

**Comment by mineo210** [comment]
@neoneggplant any update on the module since the last time you tested it? Does it work with chrome yet? just overall info :)

**Comment by neoneggplant** [comment]
I have it working for the single firefox module, but for more mac modules, you would need to ask the original developer of lazagne, I don't think it's worth including just yet
