### ISSUE TITLE
when running on ios jailbroken

### ISSUE THREAD

**Issue by mayed505** [neoneggplant/EggShell#47]
i installed python on my ios using mterminal on 10.1.1
but whenever i do python eggshell.py it says i should do easy_install pycrypto but when i do that
it still exists that error
does anyone have any deb file for pycrypto? to run the py?

**Comment by mineo210** [comment]
try installing pycrypto inside of cydia.

**Comment by mayed505** [comment]
@mineo210 pls repo?

**Comment by neoneggplant** [comment]
it's not officially supported on 64 bit iOS devices. try using from another device with python on it
