### ISSUE TITLE
getpasscode command  error "Input strings must be a multiple of 16 in length"

### ISSUE THREAD

**Issue by theHackPot** [neoneggplant/EggShell#48]
## Issue
getpasscode command fails to return passcode

### Expected behaviour
Return Passcode

### Actual behaviour
Returns error "Input strings must be a multiple of 16 in length"

### Steps to reproduce
1. Set device passcode to 4 digits e.g. 0000
2. Execute payload on target machine & connect back
3. run getpasscode command

<img width="547" alt="screen shot 2017-04-19 at 11 16 24" src="https://cloud.githubusercontent.com/assets/17269499/25175174/ba4914b6-24f1-11e7-905f-ca2c4285ec43.png">

**Comment by neoneggplant** [comment]
I will look into this, what ios version are you on?

**Comment by theHackPot** [comment]
iOS 9.0.2

**Comment by mayed505** [comment]
same im having the same issue it doesnt installpro

**Comment by neoneggplant** [comment]
eggshell 3 should fix these issues
