### ISSUE TITLE
Script freezes on certain commands on me!

### ISSUE THREAD

**Issue by mayed505** [neoneggplant/EggShell#49]
https://gyazo.com/6dce9d5e1cb6171ed03be197da55dd38
when using this command the session freezes and doesnt even take a picture on IOS
this problems applies to:
frontcam
backcam
getsms
getcontacts
getnotes
 
iphone 7 , 10.1.1
i tries also on ipad mini 1 ios 9.0.(something) still the same issue

**Comment by neoneggplant** [comment]
try on the new eggshell 3 release, it should fix this
