### ISSUE TITLE
Is possible use this code with public ip? 

### ISSUE THREAD

**Issue by angelaricas** [neoneggplant/EggShell#50]
is possible use with public ip?

**Comment by ShellBear** [comment]
Yes, but you need to forward ports (ex : 4444)  on your routeur

**Comment by angelaricas** [comment]
Where I have to put the ip publish and where I put the local ip to listen,
one more question, can I hide the path in a link? I guess, but would have
to change some other parameter for public?

Thankss!

**Comment by ShellBear** [comment]
You just need to use your public ip in eggshell, the port forward will automatically send you data from public ip to your computer on lan. This is not an url, this is a command which you need to use in terminal or insert it into an executable.

**Comment by angelaricas** [comment]
how do i insert it into a executable for ios? is not possible really?
