### ISSUE TITLE
Get Files not responding

### ISSUE THREAD

**Issue by salamsalamhavji** [neoneggplant/EggShell#59]
Hi,
when i will exec (download, frontcam, backcam , ...) command, connenction is hang up and i can not exec any command
![8-26-2017 2-20-39 pm](https://user-images.githubusercontent.com/31301048/29740351-d968866e-8a69-11e7-8010-280d969a7064.jpg)

tnx for answers.

**Comment by 30wish2015** [comment]
i get the same msg.    it seems that client sends the wrong data to server.

**Comment by Grox-Ni** [comment]
same for OS X when exec code like 'picture, ls'

**Comment by neoneggplant** [comment]
these issues will be fixed in eggshell 3

**Comment by salamsalamhavji** [comment]
that's Gooooooood.
we will wait for eggshell 3... .
Tnx man

**Comment by salamsalamhavji** [comment]
what happen in these issue? maybe i can solve it

**Comment by salamsalamhavji** [comment]
hey man, when solve this problem?

**Comment by Virgula0** [comment]
Bug appears also on Mac when eggshell tries to escalate privileges with root password...
