### ISSUE TITLE
Installpro won't work

### ISSUE THREAD

**Issue by MariusSolaat** [neoneggplant/EggShell#6]
![9b3c2d8a2104fbbe82259cfa6fb0095d](https://cloud.githubusercontent.com/assets/20828176/22852849/a615512a-f045-11e6-9fe6-f9e043c345fd.png)

This has happened to me every time I try to use installpro.

Iphone 6
Ios 10.2
Latest Yalu beta

**Comment by neoneggplant** [comment]
made some updates to the installpro command, let me know if it works now, what device do you have?

**Comment by MariusSolaat** [comment]
Newest gets stuck on "Waiting for connection" after using the payload. Both on iPhone 6 and 6S running 10.2 Yalu

**Comment by MariusSolaat** [comment]
![9b3c2d8a2104fbbe82259cfa6fb0095d](https://cloud.githubusercontent.com/assets/20828176/22905821/14701d0a-f242-11e6-8303-126fcb801ecc.png)

**Comment by neoneggplant** [comment]
I will look into it, I am going to add some debug logs to get help communicate these types of issues more in depth

**Comment by neoneggplant** [comment]
are you connecting to your external ip through a port forwarded router?

**Comment by MariusSolaat** [comment]
Yes I am, and it worked fine with the earlier versions, though installpro has never seemed to work for me. All non pro has though

**Comment by neoneggplant** [comment]
can you confirm that the payload is being executed after it is sent?

**Comment by neoneggplant** [comment]
also, is your lhost set to your public ip?

**Comment by MariusSolaat** [comment]
Where can I check if it's being executed? sorry for asking :P 

Also, the Ihost is set to my ruter's IP and the port is forwarded through my local IP. This has worked with all versions of Eggshell except this one.

**Comment by neoneggplant** [comment]
if you have terminal on the target device, you can run the command top (from cydia) and see if there is a process called ".espl"

**Comment by neoneggplant** [comment]
do you have the latest version of eggshell? with the updated binaries?

**Comment by MariusSolaat** [comment]
I am on the newest version yes. And here is a ss of the command 

![16805259_10210932334837712_1480684082_o](https://cloud.githubusercontent.com/assets/20828176/23012665/9538bbb8-f427-11e6-86ad-ff5bd638e839.jpg)

**Comment by MariusSolaat** [comment]
That' after I've run the code and waiting for connection

**Comment by neoneggplant** [comment]
ok, I was able to recreate your issue, narrowing in on what is happening

**Comment by MariusSolaat** [comment]
Sounds great! I'll wait, just tell me if you need anuthing else

**Comment by neoneggplant** [comment]
The problem ended up being the wrong ip in eggshell, for me this caused a connection to be established but since the payload was given wrong ip parameter, it would not connect back to the correct ip, leaving it stuck "waiting for connection". Also, maybe bash is stuck for you? try killall -9 bash

**Comment by MariusSolaat** [comment]
It wont let me kill it, it just says "No matching processes belonging to you were found"

**Comment by neoneggplant** [comment]
are you killing it as root?

**Comment by MariusSolaat** [comment]
I've tried both, same result

**Comment by MariusSolaat** [comment]
EDIT, when running the script as root on the phone I get connected. And all commands are working fine

**Comment by MariusSolaat** [comment]
Still nothing without running as root though

**Comment by neoneggplant** [comment]
no connection at all without root?

**Comment by neoneggplant** [comment]
ps, installpro requires root

**Comment by MariusSolaat** [comment]
Ok,. then we know why I never got installpro before, haha. But yeah, there's still no access without root.

**Comment by nerdtron123** [comment]
no connection at all without root? @neoneggplant we fixed that.

**Comment by neoneggplant** [comment]
@nerdtron123 was it changing the upload directory?

**Comment by neoneggplant** [comment]
@nerdtron123 the reason in uploaded to /usr/bin is because it would break commands listapps and sbalert if not uploaded there

**Comment by nerdtron123** [comment]
@neoneggplant that breaks non-root connections.

**Comment by neoneggplant** [comment]
yeah but there currently isn't a work around, we could check if /usr/bin is writable, and fallback to /tmp in the preload @nerdtron123

**Comment by neoneggplant** [comment]
or chmod the directory to make it writable with mobile? would that be doable?

**Comment by nerdtron123** [comment]
@neoneggplant look at my pull request

**Comment by nerdtron123** [comment]
This issue has been resolved please close it
