### ISSUE TITLE
how to use my vps ip 

### ISSUE THREAD

**Issue by uthman3a** [neoneggplant/EggShell#61]
i want a way to fix an ip and i have a vps ip is there a way to forward vps ip to my local kali in virtual machine ?

**Comment by Coriou** [comment]
Several ways to do that :

1. Run the EggShell server straight from your VPS
2. Get a domain name & configure an A DNS record pointing back to your dynamic IP (and update it when it changes) 
3. Use a service that does all the DNS setting up & allows you to easily update the IP when it changes, like [noip.com](https://www.noip.com)

**Comment by nerdtron123** [comment]
Just saying, putting it through your VPS won’t make you uncatchable, just means anyone won’t be able to track you without getting your host or the police involved

**Comment by nerdtron123** [comment]
Also, this isn’t built to leave no traces so you miight not want to use this for nefarious reasons
