### ISSUE TITLE
PLS halp me remove it thx

### ISSUE THREAD

**Issue by Scriptkidy** [neoneggplant/EggShell#62]
how do you remove it
i put it on my computer for testing and now nothing can connect on port 4444 ;-;
pls tell me how 2 remove so i can get into my friends computer and open pornhub 19384 times

thx
-scriptkidy

**Comment by Scriptkidy** [comment]
nvm i removed the crontab (`crontab -r`)
all good now 😆

**Comment by neoneggplant** [comment]
I do not condone you using it for this purpose. I denounce this behavior to the fullest
