### ISSUE TITLE
 No such file or directory: '/src/resources/esplinux

### ISSUE THREAD

**Issue by alvaroillanes** [neoneggplant/EggShell#64]
Helpme please...

binaryFile = open("/src/resources/esplinux", "rb")
IOError: [Errno 2] No such file or directory: '/src/resources/esplinux'

**Comment by Scriptkidy** [comment]
change`binaryFile = open("/src/resources/esplinux", "rb")`
to `binaryFile = open("src/resources/esplinux", "rb")`
hope this helped!
