### ISSUE TITLE
Xcode will not compile

### ISSUE THREAD

**Issue by Scriptkidy** [neoneggplant/EggShell#65]
this is a new install of eggshell with no edits or clients, any help would be appreciated.
![screen shot 2017-09-26 at 7 57 30 am](https://user-images.githubusercontent.com/26258618/30859266-ed707330-a290-11e7-9efd-69a45623f784.jpg)

**Comment by nerdtron123** [comment]
just use eggshell.py, you don’t have to compile anything

**Comment by neoneggplant** [comment]
should be fixed in 3.0 release
