### ISSUE TITLE
SSL error: [SSL: HTTP_REQUEST] http request (_ssl.c:726)

### ISSUE THREAD

**Issue by saeed9321** [neoneggplant/EggShell#85]
this error appears every time i try to execute the shell in other device.
what do you think is causing this?
even if i tried to open the lhost link in the browser manually like 192.168.100.3:4444

**Comment by Divingpig** [comment]
Any update?

**Comment by neoneggplant** [comment]
looks like your trying to open the link in the browser, you need to run the payload as a shell script or in terminal
