### ISSUE TITLE
A great job!

### ISSUE THREAD

**Issue by N1kRolexx** [neoneggplant/EggShell#89]
I have been using 2.2.1 version for a long time and it was really good and handy. I didnt check the repository for a long time because the version 3 did not work, but then i installed openssl on mac and started using it. Noticed tab-completion, correct work of all modules, encryption with a good connection speed.

_Lucas Jackson, you are doing/did a really great job and wrote an awesome tool! Have been and will be using it for a long time!_

**Comment by neoneggplant** [comment]
Thanks! I appreciate it :)
